import * as THREE from "three";
import { useRef } from "react";
import { observer } from "mobx-react-lite";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { mainStore } from "../store/MainStore";
function Ring(props: JSX.IntrinsicElements["group"]) {
  const modelRef = useRef<THREE.Group>(null!);
  const animation = !mainStore.isStopModel ? -0.001 : -0.0;
  useFrame((state, delta) => (modelRef!.current!.rotation.y += animation));
  const { nodes, materials } = useGLTF("models/strip.glb") as any;

  return (
    <group {...props} dispose={null} ref={modelRef}>
      <group rotation={[-Math.PI / 2.5, 0.2, 0.4]} scale={1.5}>
        <group position={[10, 8.65, 1.5]}>
          <points geometry={nodes.Object_2.geometry} material={materials["Scene_-_Root"]} />
          <points geometry={nodes.Object_3.geometry} material={materials["Scene_-_Root"]} />
          <points geometry={nodes.Object_4.geometry} material={materials["Scene_-_Root"]} />
          <points geometry={nodes.Object_5.geometry} material={materials["Scene_-_Root"]} />
        </group>
      </group>
    </group>
  );
}
export default observer(Ring);
useGLTF.preload("models/strip.glb");

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: stevencmutter (https://sketchfab.com/stevencmutter)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/big-tree-point-cloud-3c31d0db9cf74b4bb8ebbb5f3f32a378
title: Big Tree Point Cloud
*/
